plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'spec/dummy/**/*'

Style/BlockDelimiters:
  AllowedMethods: [lambda, proc, it, expect]

Style/FetchEnvVar:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 150

Lint/MissingSuper:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: ['x', 'y', 'w', 'h', 'km', 'to', 'id', 'db', 'as', 'io']

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  CountAsOne: ['array', 'hash', 'heredoc']

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/VariableName:
  EnforcedStyle: snake_case

RSpec/IndexedLet:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Rails/I18nLocaleTexts:
  Enabled: false
